// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVd9UDxQ-aUXJiB9UiVi3zerZ90tfzKlQ',
    appId: '1:149584078358:web:8cf2972c58c6294a98f737',
    messagingSenderId: '149584078358',
    projectId: 'realtimechatting-91bad',
    authDomain: 'realtimechatting-91bad.firebaseapp.com',
    storageBucket: 'realtimechatting-91bad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByOKrYEwl47XmY_B2yswI1dzbVcMVGEpg',
    appId: '1:149584078358:android:e1373dde226ff16498f737',
    messagingSenderId: '149584078358',
    projectId: 'realtimechatting-91bad',
    storageBucket: 'realtimechatting-91bad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl478jlARZ9PZPJE--UclyNTiHLoQh6qE',
    appId: '1:149584078358:ios:b594b355bf519ad798f737',
    messagingSenderId: '149584078358',
    projectId: 'realtimechatting-91bad',
    storageBucket: 'realtimechatting-91bad.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl478jlARZ9PZPJE--UclyNTiHLoQh6qE',
    appId: '1:149584078358:ios:b594b355bf519ad798f737',
    messagingSenderId: '149584078358',
    projectId: 'realtimechatting-91bad',
    storageBucket: 'realtimechatting-91bad.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVd9UDxQ-aUXJiB9UiVi3zerZ90tfzKlQ',
    appId: '1:149584078358:web:7a21a23452ee2eac98f737',
    messagingSenderId: '149584078358',
    projectId: 'realtimechatting-91bad',
    authDomain: 'realtimechatting-91bad.firebaseapp.com',
    storageBucket: 'realtimechatting-91bad.appspot.com',
  );

}